name: Run DCvid and DCbot

on:
  push:
    branches:
      - main

jobs:
  run-dcvid:
    runs-on: ubuntu-latest
    env: #This section is crucial for setting environment variables
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      FLASK_SECRET_KEY: ${{ secrets.DISCORD_RETRIVAL_TOKEN}} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DCvid (Flask app with Gunicorn)
        run: |
          export FLASK_APP=dcvid
          gunicorn --bind 0.0.0.0:5000 dcvid:app &
          sleep 60 #Wait for flask to initialize

      - name: Run DCbot (Discord bot)
        run: |
          python dcbot.py &
